### ISSUE TITLE
Redundant copies of the script in system/bin/ and system/xbin/

### ISSUE THREAD

**Issue by ensigma96** [Magisk-Modules-Repo/terminal_debloater_magisk#10]
There are two copies of the debloat script in `system/bin/` and `system/xbin/`, which is a bit confusing. It seems (from `config.sh`) that it comes from a special treatment for samsung devices. So if putting the script in `xbin` will work for both samsung and non-samsung devices (I don't know if that is true), maybe we can just keep one copy in `xbin`?

**Comment by veez21** [comment]
fixed
