### ISSUE TITLE
[feature request] Disable OEM apps

### ISSUE THREAD

**Issue by danielmmmm** [Magisk-Modules-Repo/terminal_debloater_magisk#11]
On Moto phones, and probably others, there is a OEM partition containing more bloat.
Would it be possible to integrate this as well?

The mountpoints are:

\oem\app
\oem\priv-app

**Comment by veez21** [comment]
Idk. Magisk only covers /system and /vendor. Is oem present in /system as well?

**Comment by danielmmmm** [comment]
Uh, I guess you are right. Unfortunately, oem is not present in /system.
Hope I manage to figure out something else :-)

**Comment by danielmmmm** [comment]
Sorry for leaving this open. I unmount the partition with a script in post-fs-data.d (in case anyone is interested).
