### ISSUE TITLE
[feature request] Show app name and apk name

### ISSUE THREAD

**Issue by danielmmmm** [Magisk-Modules-Repo/terminal_debloater_magisk#12]
On my phone, I deactivated an app called "Files", thinking it was a preinstalled file manager. It turned out to be the Documents UI, which obviously broke some things. On the other side, I found quite a lot of apps that had important looking names but turned out to be "Google waste".

Would it be helpful to not only show the app name in the list, but also the apk name or package name in parenthesis?

E.g. "Files (DocumentsUI.apk)", or "Files (com.android.documentsui)

**Comment by veez21** [comment]
It looks a bit messy imo, but I'll probably consider the apk file name.

**Comment by danielmmmm** [comment]
Great, thanks!

I don't know if these weird names came up with Android 7, or if they are special to Moto phones. I just found out that the Google SMS app "Messenger" calls itself "Bugle**DogFood**"!
