### ISSUE TITLE
Exclude list is too restrictive.

### ISSUE THREAD

**Issue by yipinghuang1991** [Magisk-Modules-Repo/terminal_debloater_magisk#14]
For example, I have a tablet that has no sim card slot.
So I debloat all telecom-related apps and Dialer.
I also debloat Contacts and ContactsProvider because I don't care about contacts on a tablet.

I think the list should only contain apps that, if debloated, would render the device inoperable;
Such as SystemUI, Shell, Settings and SettingsProvider.

**Comment by veez21** [comment]
Done
