### ISSUE TITLE
Updates are not deleted in /data/apk during debloating

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/terminal_debloater_magisk#15]
The problem appears when bloatware gets updated in Playmarket.

In this case you will have bloatware not in /system only, but in /data/app also. So when it gets removed using Debloat Script, the bloatware still remains as user application. If one tries to remove "all updates" of the bloatware the system will immediately reboot without any change, so one should restore bloatware back, remove all updates, and then debloat is again.

According to the code I supposed to see "APK stored in /data, delete?" during this process starting from Debloat v11.2, but I didn't (my version is latest 13.4).

**Comment by veez21** [comment]
Newer versions now uninstall or notify you that it needs to uninstall uodates.
