### ISSUE TITLE
Missed Analytics system app in list

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/terminal_debloater_magisk#18]
It really looks like the first entry in system apps is not displayed.
Pay attention on "Analytics" app - it is present in logs and list - but absent on screen.

Also "Engineering mode" is doubled. It wold be more informative to have ability to view the path to app to see the difference in this case.

[terminal_debloater-verbose.log](https://github.com/Magisk-Modules-Repo/terminal_debloater_magisk/files/2342380/terminal_debloater-verbose.log)
[debloat.list.log](https://github.com/Magisk-Modules-Repo/terminal_debloater_magisk/files/2342381/debloat.list.log)
![screenshot_2018-09-01-16-11-28-737_jackpal androidterm](https://user-images.githubusercontent.com/322186/44946278-0a410100-ae02-11e8-9557-b5510d213935.png)

**Comment by veez21** [comment]
That definitely seems confusing. Though adding the full path would be a clutter, maybe I'll add only the apk names just to be sure.

**Comment by gjf** [comment]
I have to add Analytics manually - mounting in recovery and editing magisk partition.
After that Analytics was"debloated", but I still wonder why it was not displayed in the list. According to logs - it should.

**Comment by fiatCurrency** [comment]
I am getting this as well, even with my little modification: the first app in the intermediate lists is getting quotes put round it.
In gjf's log, look for a line with x=114
then look at the sed line beneath it. I can't make out what it's trying to do, but having an unescaped single quote inside a single quoted regexp doesn't seem right.

**Comment by veez21** [comment]
@fiatCurrency he was using the previous debloater without the fix for list freezing

**Comment by gjf** [comment]
I have tried latest version as well - no change.
By the way I did debloat Analytics previously - so it looks like the problem appeared after some updates.
