### ISSUE TITLE
If the module is disabled the apps appears again

### ISSUE THREAD

**Issue by jperezruiz** [Magisk-Modules-Repo/terminal_debloater_magisk#8]
Is correct the behavior?
Using the debloat command I successfully uninstall Duo and Play movies. 
Restart and the apps don't appear, but, if I disable the debloat module in magisk, after reboot the device the apps appears again

**Comment by veez21** [comment]
I don't think you know how magisk works. The apps will be reinstalled back when you disable the module.

**Comment by jperezruiz** [comment]
Of course I don't know, I'm a normal user, that's why I'm asking.
